# Generated by Django 5.2.13 on 2026-04-18 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên Phim')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Ảnh bìa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField(verbose_name='Tập số')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên tập (tùy chọn)')),
                ('video_url', models.CharField(max_length=500, verbose_name='Đường dẫn file m3u8')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.movie', verbose_name='Thuộc phim')),
            ],
            options={
                'ordering': ['episode_number'],
            },
        ),
    ]
