# Generated by Django 5.2.13 on 2026-04-18 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['episode_name']},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='episode',
            name='episode_number',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='title',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_name',
            field=models.CharField(default='Tập 1', max_length=255, verbose_name='Tên Tập'),
        ),
        migrations.AddField(
            model_name='episode',
            name='m3u8_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Đường Dẫn m3u8 (HLS)'),
        ),
        migrations.AddField(
            model_name='episode',
            name='movie_file_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Đường Dẫn Video Gốc'),
        ),
        migrations.AddField(
            model_name='episode',
            name='sub_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Đường Dẫn Phụ Đề'),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True, null=True, verbose_name='Diễn Viên'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Đạo Diễn'),
        ),
        migrations.AddField(
            model_name='movie',
            name='film_format',
            field=models.CharField(choices=[('movie', 'Phim Lẻ'), ('series', 'Phim Bộ'), ('short', 'Phim Ngắn')], default='movie', max_length=20, verbose_name='Định Dạng Phim'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thể Loại'),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm IMDb'),
        ),
        migrations.AddField(
            model_name='movie',
            name='medium',
            field=models.CharField(choices=[('live_action', 'Live-Action (Người đóng)'), ('animation', 'Hoạt Hình'), ('anime', 'Anime')], default='live_action', max_length=20, verbose_name='Hình Thức Sản Xuất'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Đường Dẫn Ảnh Bìa (Poster)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Năm Phát Hành'),
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Đang Phát Sóng'), ('completed', 'Đã Hoàn Thành'), ('trailer', 'Sắp Chiếu')], default='completed', max_length=20, verbose_name='Trạng Thái'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Đường Dẫn Trailer'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.movie', verbose_name='Thuộc Phim'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô Tả'),
        ),
    ]
