# Generated by Django 5.2.13 on 2026-04-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_episode_options_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='medium',
            field=models.CharField(choices=[('live_action', 'Live-Action'), ('animation', 'Hoạt Hình'), ('anime', 'Anime')], default='live_action', max_length=20, verbose_name='Hình Thức Sản Xuất'),
        ),
    ]
