# Generated by Django 5.2.13 on 2026-04-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_medium'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['episode_number'], 'verbose_name': 'Tập Phim', 'verbose_name_plural': 'Danh Sách Tập Phim'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phim', 'verbose_name_plural': 'Danh Sách Phim'},
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Số Thứ Tự Tập'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày Tạo'),
        ),
    ]
